version: "3.8"
services:
  opt:
    image: 10.254.55.75/tenex_borehole
    build: .
    volumes:
      - tenex:/opt/gmsh/input/tenex/borehole/opt
    deploy:
      mode: replicated
      replicas: 2
      placement:
        max_replicas_per_node: 1
      resources:
        limits:
          cpus: '1.0'
          memory: 8g
        reservations:
          cpus: '1.0'
          memory: 2g

volumes:
  tenex:

